#pragma once

#include <cstdint>

#include <ZigZag/Variant.hpp>
#include <ZigZag/VariantRegisterType.hpp>


ZIGZAG_VARIANT_REGISTER_TYPE(int8_t, 1)
ZIGZAG_VARIANT_REGISTER_TYPE(int16_t, 2)
ZIGZAG_VARIANT_REGISTER_TYPE(int32_t, 3)
ZIGZAG_VARIANT_REGISTER_TYPE(int64_t, 4)

ZIGZAG_VARIANT_REGISTER_TYPE(uint8_t, 5)
ZIGZAG_VARIANT_REGISTER_TYPE(uint16_t, 6)
ZIGZAG_VARIANT_REGISTER_TYPE(uint32_t, 7)
ZIGZAG_VARIANT_REGISTER_TYPE(uint64_t, 8)

